# Borrar los anterior comandos en AMPL
reset;

# Cargar el modelo
#model C:\Users\Leo\Downloads\io\braquistocrona\var3\braq.mod;
model /Users/camibrumar/Desktop/mates2017:18/PM/io/braquistocrona/var3/braq.mod;

# Cargar los datos
#data C:\Users\Leo\Downloads\io\braquistocrona\var3\braq.dat;
data /Users/camibrumar/Desktop/mates2017:18/PM/io/braquistocrona/var3/braq.dat;


# Indicacion a ampl de que se quiere utilizar como solver: MINOS
option solver './minos';


#Resolver
option minos_options 'superbasics_limit= 1000';
solve;

#expand x[6,1,4];


# Mostrar los resultados
#option omit_zero_rows 1;

display x > /Users/camibrumar/Desktop/mates2017:18/PM/io/braquistocrona/var3/braqx.txt;
display y > /Users/camibrumar/Desktop/mates2017:18/PM/io/braquistocrona/var3/braqy.txt;
#display x,y >C:\Users\Leo\Downloads\io\braquistocrona\var3\braq.txt;
